# --- Etapa 1: Compilación ---
FROM maven:3.9.6-eclipse-temurin-17-alpine AS build
WORKDIR /app
COPY pom.xml .
RUN mvn dependency:go-offline
COPY src ./src
RUN mvn clean package -DskipTests

# --- Etapa 2: Imagen de Ejecución (Runtime) ---
FROM eclipse-temurin:17-jre-alpine
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
# CORRECCIÓN: El properties de Despachos usa el puerto 8081
EXPOSE 8081

ENTRYPOINT ["java", "-jar", "app.jar"]