name: CI/CD Pipeline - Innovatech Chile

on:
  push:
    branches:
      - main

jobs:
  deploy-all:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      # --- CONFIGURACIÓN DE LA LLAVE SSH EN EL ENTORNO LINUX ---
      - name: Configurar Agente SSH Nativo
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo -e "Host *\n\tStrictHostKeyChecking no\n\tUserKnownHostsFile /dev/null\n" > ~/.ssh/config

      # --- ETAPA 1: DESPLIEGUE EN EL FRONTEND (IP PÚBLICA) ---
      - name: Desplegar Frontend vía SSH Puro
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_FRONT_IP }} '
            cd ~/proyecto\ semestral || cd ~/Devops-prueba2 || (cd ~ && git clone https://github.com/RamiroGomeztxt/Devops-prueba2.git "proyecto semestral" && cd "proyecto semestral")
            git reset --hard HEAD
            git pull origin main
            cd front_despacho
            docker build -t frontend-app .
            docker stop frontend-container || true
            docker rm frontend-container || true
            docker run -d -p 80:80 --name frontend-container frontend-app
          '

      # --- ETAPA 2: PASAR ARCHIVOS AL BACKEND (A TRAVÉS DE LA RED PRIVADA) ---
      - name: Transferir archivos y Desplegar Backend Privado
        run: |
          # 1. Creamos el archivo temporal con la llave dentro de la EC2 del Frontend
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_FRONT_IP }} "echo '${{ secrets.SSH_PRIVATE_KEY }}' > ~/key_temporal.pem && chmod 600 ~/key_temporal.pem"
          
          # 2. Le ordenamos a la EC2 del Front que envíe los archivos a la EC2 privada del Back
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_FRONT_IP }} "
            cd ~/proyecto\ semestral || cd ~/Devops-prueba2
            ssh -i ~/key_temporal.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_BACK_PRIVATE_IP }} 'mkdir -p ~/app-backend'
            scp -i ~/key_temporal.pem -o StrictHostKeyChecking=no -r docker-compose.yml back-Despachos_SpringBoot back-Ventas_SpringBoot ${{ secrets.EC2_USER }}@${{ secrets.EC2_BACK_PRIVATE_IP }}:~/app-backend/
          "

          # 3. Le ordenamos a la EC2 del Front que se meta al Back y levante los contenedores
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_FRONT_IP }} "
            ssh -i ~/key_temporal.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_BACK_PRIVATE_IP }} '
              cd ~/app-backend
              docker-compose down || true
              docker-compose up -d --build
            '
          "

          # 4. Limpieza: Borramos la llave del Front
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_FRONT_IP }} "rm -f ~/key_temporal.pem"