name: CI/CD Pipeline - Innovatech Chile

on:
  push:
    branches:
      - main

jobs:
  deploy-all:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      # --- ETAPA 1: DESPLIEGUE EN EL FRONTEND (IP PÚBLICA) ---
      - name: Desplegar Frontend y preparar archivos de Backend
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_FRONT_IP }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          fingerprint: "" # TRUCO: Al pasarlo vacío fuerza a aceptar la llave ignorando formatos de Windows
          script: |
            cd ~/proyecto\ semestral || cd ~/Devops-prueba2 || (cd ~ && git clone https://github.com/${{ github.repository }}.git "proyecto semestral" && cd "proyecto semestral")
            
            git reset --hard HEAD
            git pull origin main

            cd front_despacho
            docker build -t frontend-app .
            docker stop frontend-container || true
            docker rm frontend-container || true
            docker run -d -p 80:80 --name frontend-container frontend-app

      # --- ETAPA 2: PASAR ARCHIVOS AL BACKEND (IP PRIVADA VIA SSH) ---
      - name: Enviar código al Backend y desplegar
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_FRONT_IP }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          fingerprint: "" # Mismo truco aquí
          proxy_host: ${{ secrets.EC2_FRONT_IP }}
          proxy_username: ${{ secrets.EC2_USER }}
          proxy_key: ${{ secrets.SSH_PRIVATE_KEY }}
          host: ${{ secrets.EC2_BACK_PRIVATE_IP }} 
          script: |
            cd ~/proyecto\ semestral || cd ~/Devops-prueba2

            echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
            chmod 600 private_key.pem

            ssh -i private_key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_BACK_PRIVATE_IP }} "mkdir -p ~/app-backend"
            scp -i private_key.pem -o StrictHostKeyChecking=no -r docker-compose.yml back-Despachos_SpringBoot back-Ventas_SpringBoot ${{ secrets.EC2_USER }}@${{ secrets.EC2_BACK_PRIVATE_IP }}:~/app-backend/

            ssh -i private_key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_BACK_PRIVATE_IP }} "
              cd ~/app-backend
              docker-compose down || true
              docker-compose up -d --build
            "

            rm -f private_key.pem